# Generated by Django 5.1.4 on 2025-01-07 09:03

from django.db import migrations

def add_categories(apps, schema_editor):
    Category = apps.get_model('lost_found_app', 'Category')
    categories = ['Clothing', 'Mobile', 'Walking accessories', 'Books', 'Opticals', 'ID']
    for category in categories:
        Category.objects.create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
