# Generated by Django 5.1.4 on 2025-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app', '0002_auto_20250107_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='vision_labels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='vision_labels',
            field=models.TextField(blank=True, null=True),
        ),
    ]
