# Generated by Django 5.1.4 on 2025-01-15 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app', '0003_founditem_vision_labels_lostitem_vision_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found_app.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found_app.lostitem')),
            ],
            options={
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
