# Generated by Django 5.1.4 on 2025-02-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found_app', '0007_alter_founditem_user_alter_lostitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
